name: "upload_COS"

###############################################################################
# This ci packages the repository files and uploads them to 
# the Tencent cloud storage bucket
###############################################################################

on:
  push:
    branches: [ main, dev ]

jobs:
  win_build_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dotnet Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Pip Install paramiko
      run: pip install paramiko

    - name: Publish
      run: | 
        mkdir -p THUAI6/win/win64/Debug
        
        dotnet publish "./logic/Server/Server.csproj" -c Release -r win-x64 -o ./THUAI6/win/win64 --self-contained true
        dotnet publish "./logic/Server/Server.csproj" -c Debug -r win-x64 -o ./THUAI6/win/win64/Debug --self-contained true

    - name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -r ./THUAI6/ /THUAI6/
        secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        bucket: ${{ secrets.COS_BUCKET }}
        region: ${{ secrets.COS_REGION }}

  linux_build_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dotnet Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Pip Install paramiko
      run: pip install paramiko

    - name: Publish
      run: |
        mkdir -p THUAI6/linux/linux64/Debug
        
        dotnet publish "./logic/Server/Server.csproj" -c Release -r linux-x64 -o ./THUAI6/linux/linux64 --self-contained true
        dotnet publish "./logic/Server/Server.csproj" -c Debug -r linux-x64 -o ./THUAI6/linux/linux64/Debug --self-contained true

    - name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -r ./THUAI6/ /THUAI6/
        secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        bucket: ${{ secrets.COS_BUCKET }}
        region: ${{ secrets.COS_REGION }}

  capi_build_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Copy CAPI
      run: |
        mkdir -p THUAI6/linux
        mkdir -p THUAI6/win/CAPI/proto
        cp ./dependency/proto/Message2Clients.proto ./THUAI6/win/CAPI/proto/
        cp ./dependency/proto/Message2Server.proto ./THUAI6/win/CAPI/proto/
        cp ./dependency/proto/Services.proto ./THUAI6/win/CAPI/proto/
        cp ./dependency/proto/MessageType.proto ./THUAI6/win/CAPI/proto/
        cp -r ./CAPI/cpp ./THUAI6/win/CAPI/
        cp -r ./CAPI/python ./THUAI6/win/CAPI/
        cp -r ./THUAI6/win/CAPI ./THUAI6/linux/

    - name: Copy shell
      run: |
        cp -r ./CAPI/cmd/* ./THUAI6/win/
        cp -r ./CAPI/shell/* ./THUAI6/linux/

    - name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -r ./THUAI6/ /THUAI6/
        secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        bucket: ${{ secrets.COS_BUCKET }}
        region: ${{ secrets.COS_REGION }}